name: Deploy to Lambda

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install and build
        eny:
          CI: true
        run:
           npm ci
           npm run build --if-present
      - name: AWS Lambda Deploy Function
  uses: zeagord/aws-lambda-deploy-function@0.0.3
